paths:
  gdp: "data/gdp.csv"
  inflation: "data/inflation.csv"
  interest: "data/interest.csv"
  leap_election: "data/leapNelection.csv"
  points: "data/sensex.csv"
  us_inr: "data/usd_inr.csv"
  dow_jones: "data/dowJones.csv"
  gold: "data/gold.csv"
  oil: "data/oil.csv"

features:
  - date
  - usinr
  - gdp
  - inflation
  - interest
  - leap
  - election
  - dow_jones
  - gold
  - oil
  - points

preprocess:
  window_length: 30
  batch_size: 32
  num_features: 10
